-name: 'gcr.io/cloud-builders/gcloud'
args:
    - functions
    - deploy
    - icici-extractor
    - --gen2
    - --runtime=python310
    - --region=asia-south1
    - --source=./Document-processing-function
    - --entry-point=hello_gcs
    - --trigger-event=google.storage.object.finalize
    - --trigger-resource=icici-kyc-source-docs-a11deef31d
    - --run-service-account=icici-gc-cf-sa@prj-icici-26.iam.gserviceaccount.com
    - --trigger-location=asia-south1
